CarStatistica/CarStatistica/Models/Car.cs
using CarStatistica.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarStatistica.Models
{
    public class Car
    {
        private int _id;
        private string _brand;
        private string _type;
        private int _actualMileage;

        public Car()
        {
            CreateDate = DateTime.Now;
        }

        public int Id
        {
            get => _id;
            set
            {
                _id = value;
                ChangeEditDate();
            }
        }
        [Display(Name = "Marka")]
        public string Brand
        {
            get => _brand;
            set
            {
                _brand = value;
                ChangeEditDate();
            }
        }
        [Display(Name = "Model")]
        public string Type
        {
            get => _type;
            set
            {
                _type = value;
                ChangeEditDate();
            }
        }
        [Display(Name = "Przebieg startowy")]
        public int StartMileage { get; set; }
        [Display(Name = "Aktualny przebieg")]
        public int ActualMileage
        {
            get => _actualMileage;
            set
            {
                _actualMileage = value;
                ChangeEditDate();
            }
        }
        [Display(Name = "Data utworzenia")]
        public DateTime CreateDate { get; }
        [Display(Name = "Ostatnia data edycji")]
        public DateTime LastEdit { get; private set; }


        public User User { get; set; }
        [Required]
        public ICollection<Refueling> Refuelings { get; set; }

        private void ChangeEditDate()
        {
            LastEdit = DateTime.Now;
        }
    }
}

CarStatistica/CarStatistica/ViewModels/CarViewModel.cs
using CarStatistica.Models;
using System.ComponentModel.DataAnnotations;

namespace CarStatistica.ViewModels
{
    public class CarViewModel
    {
        [Display(Name = "Marka")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        public string Brand { get; set; }

        [Display(Name = "Model")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        public string Type { get; set; }

        [Display(Name = "Aktualny przebieg")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        public int StartMileage { get; set; }


        public Car GetCar()
        {
            return new Car()
            {
                Brand = Brand,
                Type = Type,
                StartMileage = StartMileage
            };
        }
    }
}

CarStatistica/CarStatistica/Controllers/CarController.cs
using CarStatistica.Data;
using CarStatistica.Data.Repositories;
using CarStatistica.Models;
using CarStatistica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStatistica.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICarRepository<Car> _carRepository;
        public CarController(UserManager<User> userManager, ICarRepository<Car> carRepository)
        {
            _userManager = userManager;
            _carRepository = carRepository;

        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CarViewModel carViewModel)
        {
            if (!ModelState.IsValid)
                return View(carViewModel);

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                ModelState.AddModelError("", "Błąd użytkownika");
                return View(carViewModel);
            }

            var car = carViewModel.GetCar();
            car.User = user;
            car.ActualMileage = car.StartMileage;

            var result = await _carRepository.Add(car);

            if (!result)
            {
                ModelState.AddModelError("", "Błąd dodawania pojazdu");
                return View(carViewModel);
            }

            return RedirectToAction("index");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return View();

            var carList = await _carRepository.GetAll(user);
            return View(carList);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index");

            var carToDelete = await _carRepository.Get(id, user);

            return View(carToDelete);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index");

            var result = await _carRepository.Delete(id, user);

            if (!result)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");

        }


    }
}

CarStatistica/CarStatistica/Controllers/CostController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarStatistica.Controllers
{
    public class CostController : Controller
    {
        public IActionResult Index(int id)
        {
            return View(id);
        }
    }
}

CarStatistica/CarStatistica/Views/Car/Add.cshtml
@model CarStatistica.ViewModels.CarViewModel

@{
    ViewData["Title"] = "Dodawanie samochodu";
}



<h4>Dodaj samochód</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartMileage" class="control-label"></label>
                <input asp-for="StartMileage" class="form-control" />
                <span asp-validation-for="StartMileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wyświetl listę samochodów</a>
</div>

CarStatistica/CarStatistica/Views/Car/Delete.cshtml
@model CarStatistica.Models.Car

@{
    ViewData["Title"] = "Usuwanie samochodu";
}



<div>
    <h4>Potwierdź usunięcie.</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartMileage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartMileage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActualMileage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActualMileage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEdit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEdit)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Usuń", "ConfirmDelete", new { id = Model.Id }) |
    <a asp-action="Index">Wyświetl listę samochodów</a>
</div>

CarStatistica/CarStatistica/Views/Car/Index.cshtml
@model IEnumerable<CarStatistica.Models.Car>

@{
    ViewData["Title"] = "Lista samochodów";
}


@if (@Model.Any())
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Brand)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartMileage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ActualMileage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreateDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastEdit)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartMileage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActualMileage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastEdit)
                    </td>
                    <td>
                        @Html.ActionLink("Usuń", "Delete", new { id = item.Id }) | 
                        @Html.ActionLink("Koszty", "Index","Cost", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <span>Brak samochodów. <a asp-action="Add">Dodaj pierwszy samochód</a></span>
}