CarStatistica/CarStatistica/Controllers/CarController.cs
using CarStatistica.Data;
using CarStatistica.Data.Repositories;
using CarStatistica.Models;
using CarStatistica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStatistica.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICarRepository<Car> _carRepository;
        public CarController(UserManager<User> userManager, ICarRepository<Car> carRepository)
        {
            _userManager = userManager;
            _carRepository = carRepository;

        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CarViewModel carViewModel)
        {
            if (!ModelState.IsValid)
                return View(carViewModel);

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                ModelState.AddModelError("", "Błąd użytkownika");
                return View(carViewModel);
            }

            var car = carViewModel.GetCar();
            car.User = user;
            car.ActualMileage = car.StartMileage;

            var result = await _carRepository.Add(car);

            if (!result)
            {
                ModelState.AddModelError("", "Błąd dodawania pojazdu");
                return View(carViewModel);
            }

            return RedirectToAction("index");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return View();

            var carList = await _carRepository.GetAll(user);
            return View(carList);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index");

            var carToDelete = await _carRepository.Get(id, user);

            return View(carToDelete);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index");

            var result = await _carRepository.Delete(id, user);

            if (!result)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");

        }


    }
}

CarStatistica/CarStatistica/Controllers/LoginController.cs
using CarStatistica.Data;
using CarStatistica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStatistica.Controllers
{
    [Authorize]
    public class LoginController : Controller
    {
        private readonly SignInManager<User> _signInManager;

        public LoginController(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
                return View(loginViewModel);

            var loginResult = await _signInManager.PasswordSignInAsync(loginViewModel.Login, loginViewModel.Password,
                loginViewModel.RememberMe, false);

            if (loginResult.Succeeded == false)
            {

                ModelState.AddModelError("", "Nie można się zalogować");
                return View(loginViewModel);
            }

            return RedirectToAction("Succeed");
        }

        [HttpGet]
        public IActionResult Succeed()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

CarStatistica/CarStatistica/Controllers/RefuelingController.cs
using CarStatistica.Data;
using CarStatistica.Data.Repositories;
using CarStatistica.Models;
using CarStatistica.Service;
using CarStatistica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStatistica.Controllers
{
    [Authorize]
    public class RefuelingController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IRefuelingRepository<Refueling> _refuelingRepository;
        public RefuelingController(UserManager<User> userManager, IRefuelingRepository<Refueling> refuelingRepository)
        {
            _userManager = userManager;
            _refuelingRepository = refuelingRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index", new { id = id });

            //TempData["CarId"] = id;

            var listRefueling = await _refuelingRepository.GetAll(id, user);
            return View(listRefueling);
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            //TempData["CarId"] = id;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Add(RefuelingViewModel refuelingViewModel, int id)
        {
            if (!ModelState.IsValid)
                return View(refuelingViewModel);

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index", new { id = id });

            //TempData["CarId"] = id;

            if (await _refuelingRepository.IsRefuelingGoodOrder(refuelingViewModel.GetRefueling(), id, user) == false)
            {
                ModelState.AddModelError("", "Nie prawidłowa chronologia");
                return View(refuelingViewModel);
            }

            var result = await _refuelingRepository.Add(refuelingViewModel.GetRefueling(), id, user);

            if (!result)
            {
                ModelState.AddModelError("", "Błąd dodawania kosztów");
                return View(refuelingViewModel);
            }

            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> Average(int id)
        {
            //TempData["CarId"] = id;

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index", new { id = id });

            var refuelingList = await _refuelingRepository.GetAll(id, user);

            return View(AverageRefuelingService.GenerateAverageRefuelingList(refuelingList));
        }

        public async Task<IActionResult> Delete(int refuelingId, int carId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return RedirectToAction("Index", new { id = carId });

            var result = await _refuelingRepository.Delete(refuelingId, carId, user);
            //if (!result)
            return RedirectToAction("Index", new { id = carId });




        }
    }
}

CarStatistica/CarStatistica/Controllers/RegisterController.cs
using CarStatistica.Data;
using CarStatistica.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStatistica.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<User> _userManager;

        public RegisterController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            if (!ModelState.IsValid)
                return View(registerViewModel);

            var user = new User(registerViewModel.Login) { Email = registerViewModel.Email };

            var createResult = await _userManager.CreateAsync(user, registerViewModel.Password);

            TempData["UserName"] = registerViewModel.Login;

            if (createResult.Succeeded == false)
            {
                foreach (var error in createResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(registerViewModel);
            }

            return RedirectToAction("Succeed");
        }

        [HttpGet]
        public IActionResult Succeed(RegisterViewModel registerViewModel)
        {
            return View(registerViewModel);
        }
    }
}

CarStatistica/CarStatistica/Views/Shared/_CostNav.cshtml
<div>
    <h4>Rodzaje kosztów:</h4>

    <div class="btn-group dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tankowania
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-action="Add" asp-controller="Refueling" asp-route-id="@Model">Dodaj</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="Refueling" asp-route-id="@Model">Wyświetl</a>
            <a class="dropdown-item" asp-action="Average" asp-controller="Refueling" asp-route-id="@Model">Średnie spalanie</a>
        </div>
    </div>


    <div class="btn-group dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Zakupy
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Add" asp-controller="Purchase" asp-route-id="@Model">Dodaj</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="Purchase" asp-route-id="@Model">Wyświetl</a>
        </div>
    </div>


    <div class="btn-group dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ubezpieczenia
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Add" asp-controller="Insurance" asp-route-id="@Model">Dodaj</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="Insurance" asp-route-id="@Model">Wyświetl</a>
        </div>
    </div>

    <div class="btn-group dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Naprawy
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Add" asp-controller="Repair" asp-route-id="@Model">Dodaj</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="Repair" asp-route-id="@Model">Wyświetl</a>
        </div>
    </div>

    <div class="btn-group dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Badania techniczne
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Add" asp-controller="TechnicalReview" asp-route-id="@Model">Dodaj</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="TechnicalReview" asp-route-id="@Model">Wyświetl</a>
        </div>
    </div>


</div>

CarStatistica/CarStatistica/Views/Shared/_Layout.cshtml
<!doctype html>

<html lang="pl">
<head>
    <meta charset="utf-8">

    <title>Stat Cars</title>

    <meta name="author" content="Dawid Kolbusz">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>

<body>
    <div>
        @{
            await Html.RenderPartialAsync("_Navbar");
        }
    </div>
    <div class="container-fluid">
        @RenderBody()
    </div>

</body>
</html>

CarStatistica/CarStatistica/Views/Shared/_LoginNav.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
    <ul class="navbar-nav ml-auto">

        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <span class="navbar-text">Witaj @UserManager.GetUserName(User)!</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Login" asp-action="Logout">Wyloguj</a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Login" asp-action="Login">Zaloguj</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Register" asp-action="Register">Zarejestruj</a>
            </li>
        }
    </ul>

CarStatistica/CarStatistica/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Strona główna</a>
            </li>

            <li class="nav-item dropdown">
                @await Html.PartialAsync("_UserNav")
            </li>
        </ul>
        <div class="my-2 my-lg-0">
            @await Html.PartialAsync("_LoginNav")
        </div>
    </div>

</nav>

CarStatistica/CarStatistica/Views/Shared/_UserNav.cshtml
@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Zarządzaj
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" asp-controller="Car" asp-action="Index">Wyświetl samochody</a>
        <a class="dropdown-item" asp-controller="Car" asp-action="Add">Dodaj samochód</a>
    </div>
}